# Generated by Django 2.2.1 on 2019-05-29 17:58

import datetime
from django.db import migrations, models
import news.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('seo_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title')),
                ('desc', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, max_length=250, null=True, verbose_name='Keywords')),
                ('image', models.ImageField(upload_to=news.models.News.get_picture_url, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
