# Generated by Django 2.2.1 on 2019-06-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190529_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('date',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='short_desc',
            field=models.CharField(default=1123, max_length=250, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
