# Generated by Django 2.2.1 on 2019-05-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendedflatpage',
            options={'verbose_name': 'Простая страница', 'verbose_name_plural': 'Простые страницы'},
        ),
    ]
