# Generated by Django 2.2.1 on 2019-06-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20190529_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendedflatpage',
            options={'ordering': ['my_order'], 'verbose_name': 'Простая страница', 'verbose_name_plural': 'Простые страницы'},
        ),
        migrations.AddField(
            model_name='extendedflatpage',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
