# Generated by Django 2.2.1 on 2019-06-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20190601_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedflatpage',
            name='my_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
    ]
