# Generated by Django 2.2.1 on 2019-06-12 09:58

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20190601_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('seo_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title')),
                ('desc', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, max_length=250, null=True, verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'Cоглашение на обработку персональных данных',
                'verbose_name_plural': 'Cоглашение на обработку персональных данных',
            },
        ),
    ]
