# Generated by Django 2.2.1 on 2019-06-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='title',
            field=models.CharField(default=1, max_length=250, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
