# Generated by Django 2.2.1 on 2019-06-16 06:58

from django.db import migrations, models
import landing.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_agreement_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', tinymce.models.HTMLField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to=landing.models.AboutUs.get_picture_url, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='OurPros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=250, verbose_name='Текст')),
                ('image', models.ImageField(upload_to=landing.models.OurPros.get_picture_url, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Наш плюс',
                'verbose_name_plural': 'Наши плюсы',
            },
        ),
    ]
