# Generated by Django 2.2.1 on 2019-07-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_mailfromstring'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, verbose_name='URL')),
                ('seo_title', models.CharField(max_length=250, verbose_name='Title')),
                ('desc', models.CharField(max_length=250, verbose_name='Description')),
                ('keywords', models.CharField(max_length=250, verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'SEO title',
                'verbose_name_plural': 'SEO titles',
            },
        ),
        migrations.AlterModelOptions(
            name='mailfromstring',
            options={'verbose_name': 'Откуда отправлять письмо', 'verbose_name_plural': 'Откуда отправлять письмо'},
        ),
        migrations.AlterModelOptions(
            name='mailtostring',
            options={'verbose_name': 'Кому отправлять письмо', 'verbose_name_plural': 'Кому отправлять письмо'},
        ),
        migrations.RemoveField(
            model_name='mailfromstring',
            name='email_host',
        ),
        migrations.RemoveField(
            model_name='mailfromstring',
            name='email_host_password',
        ),
        migrations.RemoveField(
            model_name='mailfromstring',
            name='email_host_user',
        ),
        migrations.RemoveField(
            model_name='mailfromstring',
            name='email_port',
        ),
        migrations.RemoveField(
            model_name='mailfromstring',
            name='email_use_ssl',
        ),
        migrations.RemoveField(
            model_name='mailfromstring',
            name='email_use_tls',
        ),
        migrations.AddField(
            model_name='mailfromstring',
            name='host',
            field=models.CharField(default='123', max_length=250, verbose_name='EMAIL_HOST'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailfromstring',
            name='host_password',
            field=models.CharField(default='123', max_length=250, verbose_name='EMAIL_HOST_PASSWORD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailfromstring',
            name='host_user',
            field=models.EmailField(default='123', max_length=250, verbose_name='EMAIL_HOST_USER'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailfromstring',
            name='port',
            field=models.PositiveIntegerField(default='123123', verbose_name='EMAIL_PORT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailfromstring',
            name='use_ssl',
            field=models.BooleanField(default=True, verbose_name='EMAIL_USE_SSL(yandex.ru)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailfromstring',
            name='use_tls',
            field=models.BooleanField(default=True, verbose_name='EMAIL_USE_TLS(gmail.com, mail.ru)'),
            preserve_default=False,
        ),
    ]
