# Generated by Django 2.2.1 on 2019-06-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время заяки'),
        ),
    ]
