# Generated by Django 2.2.1 on 2019-06-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=250, verbose_name='E-mail'),
        ),
    ]
