# Generated by Django 2.2.1 on 2019-06-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0016_auto_20190608_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Телефон')),
                ('postcode', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Индекс')),
                ('country', models.CharField(blank=True, default='Россия', max_length=250, null=True, verbose_name='Страна')),
                ('region', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Регион')),
                ('locality', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Населенный пункт')),
                ('address', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Улица')),
                ('total_price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Итоговая стоимость')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('saved', models.BooleanField(default=False, verbose_name='Был сохранен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Цена')),
                ('total_price', models.PositiveIntegerField(blank=True, default=0, help_text='Посчитается при сохранении.', null=True, verbose_name='Стоимость')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
