# Generated by Django 2.2.1 on 2019-06-12 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0023_auto_20190608_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=250, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('postcode', models.CharField(default='', max_length=20, verbose_name='Индекс')),
                ('country', models.CharField(default='Россия', max_length=250, verbose_name='Страна')),
                ('region', models.CharField(default='', max_length=250, verbose_name='Регион / Область')),
                ('locality', models.CharField(default='', max_length=250, verbose_name='Город / Населённый пункт')),
                ('address', models.CharField(default='', max_length=250, verbose_name='Улица, дом, квартира / офис')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='Итоговая стоимость')),
                ('delivery', models.CharField(choices=[('pickup', 'Самовывоз'), ('delivery', 'Доставка')], default='pickup', max_length=250, verbose_name='Способ получения товара')),
                ('status_delivery', models.CharField(choices=[('shipped', 'Отгружено'), ('not_shipped', 'Неотгружено')], default='not_shipped', max_length=250, verbose_name='Статус доставки')),
                ('status_payment', models.CharField(choices=[('paid', 'Оплачено'), ('not_paid', 'Неоплачено')], default='not_paid', max_length=250, verbose_name='Статус оплаты')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('saved', models.BooleanField(default=False, verbose_name='Был сохранен')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('total_price', models.PositiveIntegerField(default=0, help_text='Посчитается при сохранении.', verbose_name='Стоимость')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Offer', verbose_name='Товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
