# Generated by Django 2.2.1 on 2019-06-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190610_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.PositiveIntegerField(default=0, help_text='Посчитается при сохранении.', verbose_name='Стоимость'),
        ),
    ]
