# Generated by Django 2.2.1 on 2019-06-10 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20190608_1603'),
        ('orders', '0008_auto_20190610_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Offer', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
