# Generated by Django 2.2.1 on 2019-06-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190610_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=250, verbose_name='Улица, дом, квартира / офис'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='', max_length=250, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='order',
            name='locality',
            field=models.CharField(default='', max_length=250, verbose_name='Город / Населённый пункт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(default='', max_length=20, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(default='', max_length=250, verbose_name='Регион / Область'),
        ),
    ]
