# Generated by Django 2.2.1 on 2019-06-02 08:18

from django.db import migrations, models
import django.db.models.deletion
import products.models
import smart_selects.db_fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Заполнится при сохранении', max_length=250, unique=True, verbose_name='Slug')),
                ('seo_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title')),
                ('desc', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, max_length=250, null=True, verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=250, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Заполнится при сохранении', max_length=250, unique=True, verbose_name='Slug')),
                ('seo_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title')),
                ('desc', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, max_length=250, null=True, verbose_name='Keywords')),
            ],
            options={
                'verbose_name': 'Тип товаров',
                'verbose_name_plural': 'Типы товаров',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Заполнится при сохранении', max_length=250, unique=True, verbose_name='Slug')),
                ('seo_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title')),
                ('desc', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, max_length=250, null=True, verbose_name='Keywords')),
                ('category', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='product_type', chained_model_field='product_type', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.Category', verbose_name='Категория')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductType', verbose_name='Тип товара')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('features', models.CharField(max_length=250, verbose_name='Особенности')),
                ('vendor_code', models.CharField(max_length=50, verbose_name='Артикул')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание')),
                ('slug', models.SlugField(help_text='Заполнится при сохранении', max_length=250, unique=True, verbose_name='Slug')),
                ('seo_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title')),
                ('desc', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('keywords', models.CharField(blank=True, max_length=250, null=True, verbose_name='Keywords')),
                ('category', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='product_type', chained_model_field='product_type', on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='Категория')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductType', verbose_name='Тип товара')),
                ('subcategory', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='products.SubCategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_without_sale', models.PositiveIntegerField(default=0, verbose_name='Цена без скидки')),
                ('sale', models.PositiveIntegerField(default=0, verbose_name='Скидка')),
                ('price', models.PositiveIntegerField(default=0, help_text='Заполнится при сохранении', verbose_name='Цена со скидкой')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='На складе')),
                ('purchased', models.PositiveIntegerField(default=0, verbose_name='Куплено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.ProductMaterial', verbose_name='Материал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.Product', verbose_name='Товар')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.ProductSize', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Вариант товаров',
                'verbose_name_plural': 'Варианты товаров',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.Image.get_picture_url, verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductType', verbose_name='Тип товара'),
        ),
    ]
