# Generated by Django 2.2.1 on 2019-05-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.CharField(default='123', max_length=250, verbose_name='Особенности'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(max_length=50, verbose_name='Артикул'),
        ),
    ]
