# Generated by Django 2.2.1 on 2019-05-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190529_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Вариант товаров', 'verbose_name_plural': 'Варианты товаров'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Заполнится при сохранении', verbose_name='Цена со скидкой'),
        ),
    ]
