# Generated by Django 2.2.1 on 2019-05-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190529_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название'),
        ),
    ]
