# Generated by Django 2.2.1 on 2019-06-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190602_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
    ]
