# Generated by Django 2.2.1 on 2019-06-03 17:04

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190603_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to=products.models.Category.get_picture_url, verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
