# Generated by Django 2.2.1 on 2019-06-03 17:15

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.SubCategory.get_picture_url, verbose_name='Изображение'),
        ),
    ]
