# Generated by Django 2.2.1 on 2019-06-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190605_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Наименьшая цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_without_sale',
            field=models.PositiveIntegerField(default=0, verbose_name='Наименьшая цена без скидки'),
        ),
    ]
