# Generated by Django 2.2.1 on 2019-06-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20190608_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='materials',
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.CharField(default='Пример: Кожа, Хлопок', help_text='Материалы через запятую', max_length=250, verbose_name='Материалы'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='Пример: 43, 34', help_text='Размеры через запятую', max_length=250, verbose_name='Размеры'),
        ),
    ]
