# Generated by Django 2.2.1 on 2019-06-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20190608_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.CharField(default='Кожа, Хлопок', help_text='Материалы через запятую', max_length=250, verbose_name='Материалы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='43, 34', help_text='Размеры через запятую', max_length=250, verbose_name='Размеры'),
        ),
    ]
