# Generated by Django 2.2.1 on 2019-06-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20190608_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='material',
            field=models.CharField(max_length=250, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='size',
            field=models.CharField(max_length=250, verbose_name='Размер'),
        ),
    ]
