# Generated by Django 2.2.1 on 2019-06-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20190608_1552'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('size', 'material', 'product')},
        ),
    ]
