# Generated by Django 2.2.1 on 2019-06-16 06:50

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20190616_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='image',
            field=models.ImageField(default=1, upload_to=products.models.ProductType.get_picture_url, verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
